import { useEffect, useState } from 'react';
import { CheckCircle, XCircle, RefreshCw } from 'lucide-react';

type Booking={id:number;studio_name:string;user_name:string;user_email:string;date:string;start_time:string;end_time:string;total_price:number;status:string;payment_status?:string};
export default function AdminBookings(){
 const [rows,setRows]=useState<Booking[]>([]); const [loading,setLoading]=useState(true);
 const load=()=>{setLoading(true);fetch('/api/bookings/all').then(r=>r.json()).then(setRows).finally(()=>setLoading(false));}; useEffect(load,[]);
 const update=async(id:number,status:string)=>{await fetch(`/api/bookings/${id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});load();};
 return <div className="space-y-6"><div className="flex justify-between items-center"><div><h1 className="text-2xl font-bold text-white">จัดการการจอง</h1><p className="text-zinc-500 text-sm mt-1">ยืนยันและจัดการการจองจากฐานข้อมูลจริง</p></div><button onClick={load} className="p-2 rounded-lg bg-white/5 text-zinc-300"><RefreshCw className="w-4 h-4"/></button></div>
 <div className="bg-[#111114] border border-white/6 rounded-xl overflow-auto"><table className="w-full text-sm"><thead><tr className="text-zinc-500 border-b border-white/6"><th className="p-4 text-left">ลูกค้า</th><th className="p-4 text-left">ห้อง</th><th className="p-4 text-left">วัน/เวลา</th><th className="p-4 text-left">ราคา</th><th className="p-4 text-left">สถานะ</th><th className="p-4 text-right">จัดการ</th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="p-8 text-center text-zinc-500">กำลังโหลด...</td></tr>:rows.map(b=><tr key={b.id} className="border-b border-white/4"><td className="p-4"><div className="text-white">{b.user_name}</div><div className="text-xs text-zinc-500">{b.user_email}</div></td><td className="p-4 text-zinc-300">{b.studio_name}</td><td className="p-4 text-zinc-300">{b.date}<br/>{b.start_time}–{b.end_time}</td><td className="p-4 text-white">฿{b.total_price}</td><td className="p-4"><span className="px-2 py-1 rounded-full bg-white/5 text-zinc-300">{b.status}</span></td><td className="p-4 text-right">{b.status==='pending'&&<div className="flex justify-end gap-2"><button onClick={()=>update(b.id,'confirmed')} className="px-3 py-2 rounded-lg bg-green-500/10 text-green-400"><CheckCircle className="w-4 h-4 inline mr-1"/>ยืนยัน</button><button onClick={()=>update(b.id,'cancelled')} className="px-3 py-2 rounded-lg bg-red-500/10 text-red-400"><XCircle className="w-4 h-4 inline mr-1"/>ยกเลิก</button></div>}</td></tr>)}</tbody></table></div></div>;
}
