import { useEffect, useState } from 'react';
import { CheckCircle2, Clock3, RefreshCw, Wrench } from 'lucide-react';

type S={id:number;name:string;status:string;price_per_hour:number;description?:string;equipment?:string;image_url?:string};
export default function AdminRoomStatus(){
 const [rooms,setRooms]=useState<S[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<number|null>(null);const [error,setError]=useState('');
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/studios');const x=await r.json();if(!r.ok)throw new Error(x.error||'โหลดข้อมูลไม่สำเร็จ');setRooms(x)}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const toggle=async(s:S)=>{setBusy(s.id);try{const r=await fetch(`/api/studios/${s.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...s,status:s.status==='maintenance'?'available':'maintenance'})});const x=await r.json();if(!r.ok)throw new Error(x.error||'เปลี่ยนสถานะไม่สำเร็จ');setRooms(v=>v.map(x=>x.id===s.id?x:v))}catch(e:any){setError(e.message)}finally{setBusy(null)}};
 return <div className="space-y-6"><div className="flex justify-between gap-3"><div><h1 className="text-2xl font-bold text-white">สถานะห้องซ้อม</h1><p className="text-zinc-500 text-sm mt-1">เปิด/ปิดให้บริการห้องจากระบบจริง</p></div><button onClick={load} className="p-2 rounded-lg bg-white/5 text-zinc-300"><RefreshCw className="w-4 h-4"/></button></div>{error&&<div className="bg-red-500/10 border border-red-500/20 rounded-xl p-3 text-red-300 text-sm">{error}</div>}{loading?<div className="text-zinc-500">กำลังโหลด...</div>:<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{rooms.map(r=><div key={r.id} className="bg-[#111114] border border-white/6 rounded-2xl p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className={`p-2 rounded-xl ${r.status==='maintenance'?'bg-orange-500/10':'bg-emerald-500/10'}`}>{r.status==='maintenance'?<Wrench className="w-5 h-5 text-orange-400"/>:<CheckCircle2 className="w-5 h-5 text-emerald-400"/>}</div><div><h3 className="text-white font-semibold">{r.name}</h3><p className="text-xs text-zinc-500">฿{r.price_per_hour}/ชม.</p></div></div><span className={`text-xs px-2 py-1 rounded-full ${r.status==='maintenance'?'bg-orange-500/10 text-orange-400':'bg-emerald-500/10 text-emerald-400'}`}>{r.status==='maintenance'?'ปิดปรับปรุง':'พร้อมให้บริการ'}</span></div><p className="text-zinc-500 text-sm mt-4">{r.description||'ไม่มีรายละเอียด'}</p><button disabled={busy===r.id} onClick={()=>toggle(r)} className="mt-5 w-full border border-white/10 rounded-xl py-2.5 text-zinc-300 hover:bg-white/5 disabled:opacity-50">{busy===r.id?'กำลังบันทึก...':r.status==='maintenance'?'เปิดให้บริการ':'ปิดปรับปรุง'}</button></div>)}</div>}</div>
}
