import { useEffect, useState } from 'react';
import { Banknote, Building2, CreditCard, Eye, EyeOff, Save, User, RefreshCw } from 'lucide-react';

type Tab='โปรไฟล์'|'สตูดิโอ'|'ราคา'|'การชำระเงิน';
const TABS:Tab[]=['โปรไฟล์','สตูดิโอ','ราคา','การชำระเงิน'];
const defaults:any={profile:{name:'',email:'',phone:'',currentPassword:'',newPassword:''},studio:{name:'Music Studio',address:'',phone:'',email:'',openTime:'08:00',closeTime:'23:00',description:''},pricing:{basePrice:300,weekendMarkup:20,depositPercent:30,minHours:1,maxHours:8},payments:{scb:true,kbank:true,bbl:false,ttb:false,promptpay:true,accountName:'',accountNumber:''}};
export default function AdminSettings(){
 const [tab,setTab]=useState<Tab>('โปรไฟล์');const [data,setData]=useState<any>(defaults);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [saved,setSaved]=useState('');const [error,setError]=useState('');const [showCurrent,setShowCurrent]=useState(false);const [showNew,setShowNew]=useState(false);
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/admin/settings');const x=await r.json();if(!r.ok)throw new Error(x.error||'โหลดการตั้งค่าไม่สำเร็จ');setData({...defaults,...x,profile:{...defaults.profile,...x.profile},studio:{...defaults.studio,...x.studio},pricing:{...defaults.pricing,...x.pricing},payments:{...defaults.payments,...x.payments}})}catch(e:any){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const save=async()=>{setSaving(true);setError('');setSaved('');try{const profile={...data.profile};const r1=await fetch('/api/admin/profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)});const p=await r1.json();if(!r1.ok)throw new Error(p.error||'บันทึกโปรไฟล์ไม่สำเร็จ');const r2=await fetch('/api/admin/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const x=await r2.json();if(!r2.ok)throw new Error(x.error||'บันทึกการตั้งค่าไม่สำเร็จ');setData((d:any)=>({...d,profile:{...d.profile,currentPassword:'',newPassword:''}}));setSaved('บันทึกสำเร็จแล้ว ✓');setTimeout(()=>setSaved(''),2500)}catch(e:any){setError(e.message)}finally{setSaving(false)}};
 const input='w-full bg-white/4 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white focus:outline-none focus:border-violet-500/50';const label='text-xs text-zinc-400 mb-1.5 block';
 if(loading)return <div className="text-zinc-500">กำลังโหลดการตั้งค่า...</div>;
 return <div className="space-y-6"><div className="flex justify-between gap-3"><div><h1 className="text-2xl font-bold text-white">ตั้งค่าระบบ</h1><p className="text-zinc-500 text-sm mt-1">ข้อมูลจะถูกบันทึกลงฐานข้อมูลของ Music Studio</p></div><button onClick={load} className="p-2 rounded-lg bg-white/5 text-zinc-300"><RefreshCw className="w-4 h-4"/></button></div>{error&&<div className="bg-red-500/10 border border-red-500/20 rounded-xl p-3 text-red-300 text-sm">{error}</div>}<div className="flex gap-1 bg-[#111114] border border-white/8 p-1 rounded-xl w-fit flex-wrap">{TABS.map(t=><button key={t} onClick={()=>setTab(t)} className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm ${tab===t?'bg-violet-600 text-white':'text-zinc-400 hover:text-white'}`}>{t==='โปรไฟล์'?<User className="w-4 h-4"/>:t==='สตูดิโอ'?<Building2 className="w-4 h-4"/>:t==='ราคา'?<Banknote className="w-4 h-4"/>:<CreditCard className="w-4 h-4"/>}{t}</button>)}</div><div className="bg-[#111114] border border-white/6 rounded-2xl p-6">
 {tab==='โปรไฟล์'&&<div className="max-w-lg space-y-4"><div><label className={label}>ชื่อ Admin</label><input className={input} value={data.profile.name} onChange={e=>setData((d:any)=>({...d,profile:{...d.profile,name:e.target.value}}))}/></div><div><label className={label}>Email</label><input className={input} type="email" value={data.profile.email} onChange={e=>setData((d:any)=>({...d,profile:{...d.profile,email:e.target.value}}))}/></div><div><label className={label}>เบอร์โทร</label><input className={input} value={data.profile.phone} onChange={e=>setData((d:any)=>({...d,profile:{...d.profile,phone:e.target.value}}))}/></div><div className="border-t border-white/8 pt-5 space-y-4"><p className="text-sm font-semibold text-zinc-300">เปลี่ยนรหัสผ่าน</p><div className="relative"><label className={label}>รหัสผ่านปัจจุบัน</label><input className={input+' pr-10'} type={showCurrent?'text':'password'} value={data.profile.currentPassword} onChange={e=>setData((d:any)=>({...d,profile:{...d.profile,currentPassword:e.target.value}}))}/><button onClick={()=>setShowCurrent(!showCurrent)} className="absolute right-3 bottom-2.5 text-zinc-500">{showCurrent?<EyeOff className="w-4 h-4"/>:<Eye className="w-4 h-4"/>}</button></div><div className="relative"><label className={label}>รหัสผ่านใหม่</label><input className={input+' pr-10'} type={showNew?'text':'password'} value={data.profile.newPassword} onChange={e=>setData((d:any)=>({...d,profile:{...d.profile,newPassword:e.target.value}}))}/><button onClick={()=>setShowNew(!showNew)} className="absolute right-3 bottom-2.5 text-zinc-500">{showNew?<EyeOff className="w-4 h-4"/>:<Eye className="w-4 h-4"/>}</button></div></div></div>}
 {tab==='สตูดิโอ'&&<div className="max-w-lg space-y-4">{[['name','ชื่อสตูดิโอ'],['address','ที่อยู่'],['phone','เบอร์โทร'],['email','Email'],['description','รายละเอียด']].map(([k,l])=><div key={k}><label className={label}>{l}</label>{k==='address'||k==='description'?<textarea className={input+' min-h-24'} value={data.studio[k]} onChange={e=>setData((d:any)=>({...d,studio:{...d.studio,[k]:e.target.value}}))}/>:<input className={input} value={data.studio[k]} onChange={e=>setData((d:any)=>({...d,studio:{...d.studio,[k]:e.target.value}}))}/>}</div>)}<div className="grid grid-cols-2 gap-4"><div><label className={label}>เวลาเปิด</label><input type="time" className={input} value={data.studio.openTime} onChange={e=>setData((d:any)=>({...d,studio:{...d.studio,openTime:e.target.value}}))}/></div><div><label className={label}>เวลาปิด</label><input type="time" className={input} value={data.studio.closeTime} onChange={e=>setData((d:any)=>({...d,studio:{...d.studio,closeTime:e.target.value}}))}/></div></div></div>}
 {tab==='ราคา'&&<div className="max-w-lg grid grid-cols-2 gap-4">{[['basePrice','ราคาเริ่มต้น'],['weekendMarkup','เพิ่มวันหยุด (%)'],['depositPercent','เงินมัดจำ (%)'],['minHours','ชั่วโมงขั้นต่ำ'],['maxHours','ชั่วโมงสูงสุด']].map(([k,l])=><div key={k}><label className={label}>{l}</label><input type="number" min="0" className={input} value={data.pricing[k]} onChange={e=>setData((d:any)=>({...d,pricing:{...d.pricing,[k]:Number(e.target.value)}}))}/></div>)}</div>}
 {tab==='การชำระเงิน'&&<div className="max-w-lg space-y-5"><div>{[['scb','SCB'],['kbank','KBank'],['bbl','BBL'],['ttb','TTB'],['promptpay','PromptPay']].map(([k,l])=><label key={k} className="flex items-center gap-3 p-3 mb-2 bg-white/3 border border-white/6 rounded-xl text-zinc-300"><input type="checkbox" checked={!!data.payments[k]} onChange={e=>setData((d:any)=>({...d,payments:{...d.payments,[k]:e.target.checked}}))}/>{l}</label>)}</div><div className="border-t border-white/8 pt-5 space-y-4"><div><label className={label}>ชื่อบัญชี</label><input className={input} value={data.payments.accountName} onChange={e=>setData((d:any)=>({...d,payments:{...d.payments,accountName:e.target.value}}))}/></div><div><label className={label}>เลขที่บัญชี</label><input className={input} value={data.payments.accountNumber} onChange={e=>setData((d:any)=>({...d,payments:{...d.payments,accountNumber:e.target.value}}))}/></div></div></div>}
 </div><div className="flex items-center gap-4"><button disabled={saving} onClick={save} className="flex items-center gap-2 bg-violet-600 hover:bg-violet-500 disabled:opacity-50 text-white px-6 py-2.5 rounded-xl"><Save className="w-4 h-4"/>{saving?'กำลังบันทึก...':'บันทึกการเปลี่ยนแปลง'}</button>{saved&&<span className="text-sm text-emerald-400">{saved}</span>}</div></div>
}
